---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: 'Update all packages to their latest version'
  apt:
    upgrade: dist
  become: yes
