---
- name: 'Instala pacotes de dependência do SO'
  apt:
    name:
      - python-mysqldb
      - mysql-server-5.7
      - python-pymysql
    state: latest
  become: yes

- name: 'Cria o banco mysql'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    login_unix_socket: "{{ mysql_socket }}"
    state: present
  become: yes

- name: 'Criar usuário do MYSQL'
  mysql_user:
    login_user: root
    login_unix_socket: "{{ mysql_socket }}"
    name: "{{ wp_user_name }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ wp_host_ip }}"
  become: yes

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: '/vagrant/roles/mysql/files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql
